<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <RootNamespace>AutoPlay.App</RootNamespace>
    <AssemblyName>AutoPlay</AssemblyName>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoPlay.Core\AutoPlay.Core.csproj" />
    <ProjectReference Include="..\AutoPlay.Vision\AutoPlay.Vision.csproj" />
    <ProjectReference Include="..\AutoPlay.Windows\AutoPlay.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
  </ItemGroup>

</Project>
